### ISSUE TITLE
Airsim Development Environment Setup

### ISSUE THREAD

**Issue by adrianosorio** [ECSP-Drone-Swarming-Capstone/Developer-Sandbox#3]
This task is focused on creating a simple hello world Airsim program to verify we can create code and execute it within the Airsim environment. Thier should also be instructions on how to accomplish this as well created to help guide others in executing their program.

**Comment by sleepsheee** [comment]
https://docs.google.com/document/d/1D6YXpzS3zmTqX8-2H0z3b4Tl192SUIqhdSeC3T5qT4U/edit?usp=drive_link

**Comment by adrianosorio** [comment]
Great work this will be super helpful for implementation
